apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "securelearn.fullname" . }}-config
  labels:
    {{- include "securelearn.labels" . | nindent 4 }}
data:
  CLIENT_URL: {{ .Values.clientUrl | quote }}
  API_URL: {{ .Values.apiUrl | quote }}
  SOCKET_CORS_ORIGIN: {{ .Values.socketCorsOrigin | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
