image:
  tag: "local"

clientUrl: "http://localhost:5173"
apiUrl: "http://localhost:30681"
socketCorsOrigin: "http://localhost:5173"


kong:
  service:
    type: NodePort

backend:
  replicas: 1

redis:
  enabled: true

rabbitmq:
  enabled: true
